package regression;
import org.safs.model.Component;
import org.safs.model.tools.RuntimeDataAware;
import org.safs.tools.RuntimeDataInterface;

/** *** DO NOT EDIT THIS FILE ***<br>
    THIS FILE IS GENERATED AUTOMATICALLY by org.safs.model.tools.ComponentGenerator!<br><p>
    A JSAFS AppMap reference for SAFS App Map: 'C:/SeleniumPlusDev/SeleniumPlus-REGRESSION/Maps' */
public final class Map implements RuntimeDataAware {

    private static RuntimeDataInterface dataInterface = null;

    /** Called internally as part of the bootstrap process of Dependency Injection. */
    public void setRuntimeDataInterface(RuntimeDataInterface helper){
        dataInterface = helper;
    }

    // The Names of ApplicationConstants:

    /** "DOJO_CHART_URL" */
    public static final String DOJO_CHART_URL = "DOJO_CHART_URL";

    /** The resolved runtime value of constant 'DOJO_CHART_URL', or null. */
    public static String DOJO_CHART_URL(){
        try{ return dataInterface.getVariable("DOJO_CHART_URL"); }
        catch(Exception x){ return null; }
    }

    /** "subarea" */
    public static final String subarea = "subarea";

    /** The resolved runtime value of constant 'subarea', or null. */
    public static String subarea(){
        try{ return dataInterface.getVariable("subarea"); }
        catch(Exception x){ return null; }
    }

    /** "LocationKey" */
    public static final String LocationKey = "LocationKey";

    /** The resolved runtime value of constant 'LocationKey', or null. */
    public static String LocationKey(){
        try{ return dataInterface.getVariable("LocationKey"); }
        catch(Exception x){ return null; }
    }

    /** "W3CConfirmURL" */
    public static final String W3CConfirmURL = "W3CConfirmURL";

    /** The resolved runtime value of constant 'W3CConfirmURL', or null. */
    public static String W3CConfirmURL(){
        try{ return dataInterface.getVariable("W3CConfirmURL"); }
        catch(Exception x){ return null; }
    }

    /** "GOJS_MINIMAL_URL" */
    public static final String GOJS_MINIMAL_URL = "GOJS_MINIMAL_URL";

    /** The resolved runtime value of constant 'GOJS_MINIMAL_URL', or null. */
    public static String GOJS_MINIMAL_URL(){
        try{ return dataInterface.getVariable("GOJS_MINIMAL_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_PRODUCT_URL" */
    public static final String THOMAS_BAYER_SQLREST_PRODUCT_URL = "THOMAS_BAYER_SQLREST_PRODUCT_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_PRODUCT_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_PRODUCT_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_PRODUCT_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_INVOICE_URL" */
    public static final String THOMAS_BAYER_SQLREST_INVOICE_URL = "THOMAS_BAYER_SQLREST_INVOICE_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_INVOICE_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_INVOICE_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_INVOICE_URL"); }
        catch(Exception x){ return null; }
    }

    /** "HtmlLinkTargetPageURL" */
    public static final String HtmlLinkTargetPageURL = "HtmlLinkTargetPageURL";

    /** The resolved runtime value of constant 'HtmlLinkTargetPageURL', or null. */
    public static String HtmlLinkTargetPageURL(){
        try{ return dataInterface.getVariable("HtmlLinkTargetPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_ITEM_URL" */
    public static final String THOMAS_BAYER_SQLREST_ITEM_URL = "THOMAS_BAYER_SQLREST_ITEM_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_ITEM_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_ITEM_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_ITEM_URL"); }
        catch(Exception x){ return null; }
    }

    /** "W3CAlertURL" */
    public static final String W3CAlertURL = "W3CAlertURL";

    /** The resolved runtime value of constant 'W3CAlertURL', or null. */
    public static String W3CAlertURL(){
        try{ return dataInterface.getVariable("W3CAlertURL"); }
        catch(Exception x){ return null; }
    }

    /** "InternalSecondPageURL" */
    public static final String InternalSecondPageURL = "InternalSecondPageURL";

    /** The resolved runtime value of constant 'InternalSecondPageURL', or null. */
    public static String InternalSecondPageURL(){
        try{ return dataInterface.getVariable("InternalSecondPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "W3CPromptURL" */
    public static final String W3CPromptURL = "W3CPromptURL";

    /** The resolved runtime value of constant 'W3CPromptURL', or null. */
    public static String W3CPromptURL(){
        try{ return dataInterface.getVariable("W3CPromptURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_URL" */
    public static final String THOMAS_BAYER_URL = "THOMAS_BAYER_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_URL', or null. */
    public static String THOMAS_BAYER_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_URL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_CUSTOMER_URL" */
    public static final String THOMAS_BAYER_SQLREST_CUSTOMER_URL = "THOMAS_BAYER_SQLREST_CUSTOMER_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_CUSTOMER_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_CUSTOMER_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_CUSTOMER_URL"); }
        catch(Exception x){ return null; }
    }

    /** "InternalTestLinkPageURL" */
    public static final String InternalTestLinkPageURL = "InternalTestLinkPageURL";

    /** The resolved runtime value of constant 'InternalTestLinkPageURL', or null. */
    public static String InternalTestLinkPageURL(){
        try{ return dataInterface.getVariable("InternalTestLinkPageURL"); }
        catch(Exception x){ return null; }
    }

    /** "THOMAS_BAYER_SQLREST_URL" */
    public static final String THOMAS_BAYER_SQLREST_URL = "THOMAS_BAYER_SQLREST_URL";

    /** The resolved runtime value of constant 'THOMAS_BAYER_SQLREST_URL', or null. */
    public static String THOMAS_BAYER_SQLREST_URL(){
        try{ return dataInterface.getVariable("THOMAS_BAYER_SQLREST_URL"); }
        catch(Exception x){ return null; }
    }

    /** "SwingAppID" */
    public static final String SwingAppID = "SwingAppID";

    /** The resolved runtime value of constant 'SwingAppID', or null. */
    public static String SwingAppID(){
        try{ return dataInterface.getVariable("SwingAppID"); }
        catch(Exception x){ return null; }
    }

    /** "SwingAppJar" */
    public static final String SwingAppJar = "SwingAppJar";

    /** The resolved runtime value of constant 'SwingAppJar', or null. */
    public static String SwingAppJar(){
        try{ return dataInterface.getVariable("SwingAppJar"); }
        catch(Exception x){ return null; }
    }

    /** "UserNamespaceURIBench" */
    public static final String UserNamespaceURIBench = "UserNamespaceURIBench";

    /** The resolved runtime value of constant 'UserNamespaceURIBench', or null. */
    public static String UserNamespaceURIBench(){
        try{ return dataInterface.getVariable("UserNamespaceURIBench"); }
        catch(Exception x){ return null; }
    }

    /** "HoneycombURL" */
    public static final String HoneycombURL = "HoneycombURL";

    /** The resolved runtime value of constant 'HoneycombURL', or null. */
    public static String HoneycombURL(){
        try{ return dataInterface.getVariable("HoneycombURL"); }
        catch(Exception x){ return null; }
    }

    /** "TestPath" */
    public static final String TestPath = "TestPath";

    /** The resolved runtime value of constant 'TestPath', or null. */
    public static String TestPath(){
        try{ return dataInterface.getVariable("TestPath"); }
        catch(Exception x){ return null; }
    }

    /** "SignInInfoScreenshot" */
    public static final String SignInInfoScreenshot = "SignInInfoScreenshot";

    /** The resolved runtime value of constant 'SignInInfoScreenshot', or null. */
    public static String SignInInfoScreenshot(){
        try{ return dataInterface.getVariable("SignInInfoScreenshot"); }
        catch(Exception x){ return null; }
    }

    /** "SignInBenchmark" */
    public static final String SignInBenchmark = "SignInBenchmark";

    /** The resolved runtime value of constant 'SignInBenchmark', or null. */
    public static String SignInBenchmark(){
        try{ return dataInterface.getVariable("SignInBenchmark"); }
        catch(Exception x){ return null; }
    }

    /** "GoogleUser" */
    public static final String GoogleUser = "GoogleUser";

    /** The resolved runtime value of constant 'GoogleUser', or null. */
    public static String GoogleUser(){
        try{ return dataInterface.getVariable("GoogleUser"); }
        catch(Exception x){ return null; }
    }

    /** "HoneycombBrowser" */
    public static final String HoneycombBrowser = "HoneycombBrowser";

    /** The resolved runtime value of constant 'HoneycombBrowser', or null. */
    public static String HoneycombBrowser(){
        try{ return dataInterface.getVariable("HoneycombBrowser"); }
        catch(Exception x){ return null; }
    }

    /** "GooglePassword" */
    public static final String GooglePassword = "GooglePassword";

    /** The resolved runtime value of constant 'GooglePassword', or null. */
    public static String GooglePassword(){
        try{ return dataInterface.getVariable("GooglePassword"); }
        catch(Exception x){ return null; }
    }

    /** "Platform" */
    public static final String Platform = "Platform";

    /** The resolved runtime value of constant 'Platform', or null. */
    public static String Platform(){
        try{ return dataInterface.getVariable("Platform"); }
        catch(Exception x){ return null; }
    }

    /** "SignInScreenshot" */
    public static final String SignInScreenshot = "SignInScreenshot";

    /** The resolved runtime value of constant 'SignInScreenshot', or null. */
    public static String SignInScreenshot(){
        try{ return dataInterface.getVariable("SignInScreenshot"); }
        catch(Exception x){ return null; }
    }

    /** "BingURL" */
    public static final String BingURL = "BingURL";

    /** The resolved runtime value of constant 'BingURL', or null. */
    public static String BingURL(){
        try{ return dataInterface.getVariable("BingURL"); }
        catch(Exception x){ return null; }
    }

    /** "UserNamespaceURIOut" */
    public static final String UserNamespaceURIOut = "UserNamespaceURIOut";

    /** The resolved runtime value of constant 'UserNamespaceURIOut', or null. */
    public static String UserNamespaceURIOut(){
        try{ return dataInterface.getVariable("UserNamespaceURIOut"); }
        catch(Exception x){ return null; }
    }

    /** "Browser" */
    public static final String Browser = "Browser";

    /** The resolved runtime value of constant 'Browser', or null. */
    public static String Browser(){
        try{ return dataInterface.getVariable("Browser"); }
        catch(Exception x){ return null; }
    }

    /** "EVBBPassword" */
    public static final String EVBBPassword = "EVBBPassword";

    /** The resolved runtime value of constant 'EVBBPassword', or null. */
    public static String EVBBPassword(){
        try{ return dataInterface.getVariable("EVBBPassword"); }
        catch(Exception x){ return null; }
    }

    /** "EVUserName" */
    public static final String EVUserName = "EVUserName";

    /** The resolved runtime value of constant 'EVUserName', or null. */
    public static String EVUserName(){
        try{ return dataInterface.getVariable("EVUserName"); }
        catch(Exception x){ return null; }
    }

    /** "nlsSignin" */
    public static final String nlsSignin = "nlsSignin";

    /** The resolved runtime value of constant 'nlsSignin', or null. */
    public static String nlsSignin(){
        try{ return dataInterface.getVariable("nlsSignin"); }
        catch(Exception x){ return null; }
    }

    /** "GoogleBrowser" */
    public static final String GoogleBrowser = "GoogleBrowser";

    /** The resolved runtime value of constant 'GoogleBrowser', or null. */
    public static String GoogleBrowser(){
        try{ return dataInterface.getVariable("GoogleBrowser"); }
        catch(Exception x){ return null; }
    }

    /** "MessagesURL" */
    public static final String MessagesURL = "MessagesURL";

    /** The resolved runtime value of constant 'MessagesURL', or null. */
    public static String MessagesURL(){
        try{ return dataInterface.getVariable("MessagesURL"); }
        catch(Exception x){ return null; }
    }

    /** "EVBBUserName" */
    public static final String EVBBUserName = "EVBBUserName";

    /** The resolved runtime value of constant 'EVBBUserName', or null. */
    public static String EVBBUserName(){
        try{ return dataInterface.getVariable("EVBBUserName"); }
        catch(Exception x){ return null; }
    }

    /** "ContentSelectorURL" */
    public static final String ContentSelectorURL = "ContentSelectorURL";

    /** The resolved runtime value of constant 'ContentSelectorURL', or null. */
    public static String ContentSelectorURL(){
        try{ return dataInterface.getVariable("ContentSelectorURL"); }
        catch(Exception x){ return null; }
    }

    /** "BusyDialogURL" */
    public static final String BusyDialogURL = "BusyDialogURL";

    /** The resolved runtime value of constant 'BusyDialogURL', or null. */
    public static String BusyDialogURL(){
        try{ return dataInterface.getVariable("BusyDialogURL"); }
        catch(Exception x){ return null; }
    }

    /** "TopLeft" */
    public static final String TopLeft = "TopLeft";

    /** The resolved runtime value of constant 'TopLeft', or null. */
    public static String TopLeft(){
        try{ return dataInterface.getVariable("TopLeft"); }
        catch(Exception x){ return null; }
    }

    /** "SimpleTableURL" */
    public static final String SimpleTableURL = "SimpleTableURL";

    /** The resolved runtime value of constant 'SimpleTableURL', or null. */
    public static String SimpleTableURL(){
        try{ return dataInterface.getVariable("SimpleTableURL"); }
        catch(Exception x){ return null; }
    }

    /** "GoogleURL" */
    public static final String GoogleURL = "GoogleURL";

    /** The resolved runtime value of constant 'GoogleURL', or null. */
    public static String GoogleURL(){
        try{ return dataInterface.getVariable("GoogleURL"); }
        catch(Exception x){ return null; }
    }

    /** "BenchPath" */
    public static final String BenchPath = "BenchPath";

    /** The resolved runtime value of constant 'BenchPath', or null. */
    public static String BenchPath(){
        try{ return dataInterface.getVariable("BenchPath"); }
        catch(Exception x){ return null; }
    }

    /** "EVPassword" */
    public static final String EVPassword = "EVPassword";

    /** The resolved runtime value of constant 'EVPassword', or null. */
    public static String EVPassword(){
        try{ return dataInterface.getVariable("EVPassword"); }
        catch(Exception x){ return null; }
    }

    /** "TestBrowserName" */
    public static final String TestBrowserName = "TestBrowserName";

    /** The resolved runtime value of constant 'TestBrowserName', or null. */
    public static String TestBrowserName(){
        try{ return dataInterface.getVariable("TestBrowserName"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtable2" */
    public static final String Tab_jtable2 = "Tab_jtable2";

    /** The resolved runtime value of constant 'Tab_jtable2', or null. */
    public static String Tab_jtable2(){
        try{ return dataInterface.getVariable("Tab_jtable2"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtable" */
    public static final String Tab_jtable = "Tab_jtable";

    /** The resolved runtime value of constant 'Tab_jtable', or null. */
    public static String Tab_jtable(){
        try{ return dataInterface.getVariable("Tab_jtable"); }
        catch(Exception x){ return null; }
    }

    /** "FilteredAreas2" */
    public static final String FilteredAreas2 = "FilteredAreas2";

    /** The resolved runtime value of constant 'FilteredAreas2', or null. */
    public static String FilteredAreas2(){
        try{ return dataInterface.getVariable("FilteredAreas2"); }
        catch(Exception x){ return null; }
    }

    /** "FilteredAreas1" */
    public static final String FilteredAreas1 = "FilteredAreas1";

    /** The resolved runtime value of constant 'FilteredAreas1', or null. */
    public static String FilteredAreas1(){
        try{ return dataInterface.getVariable("FilteredAreas1"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_mort_calc" */
    public static final String Tab_mort_calc = "Tab_mort_calc";

    /** The resolved runtime value of constant 'Tab_mort_calc', or null. */
    public static String Tab_mort_calc(){
        try{ return dataInterface.getVariable("Tab_mort_calc"); }
        catch(Exception x){ return null; }
    }

    /** "locationA" */
    public static final String locationA = "locationA";

    /** The resolved runtime value of constant 'locationA', or null. */
    public static String locationA(){
        try{ return dataInterface.getVariable("locationA"); }
        catch(Exception x){ return null; }
    }

    /** "SAPDemoURL" */
    public static final String SAPDemoURL = "SAPDemoURL";

    /** The resolved runtime value of constant 'SAPDemoURL', or null. */
    public static String SAPDemoURL(){
        try{ return dataInterface.getVariable("SAPDemoURL"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtree" */
    public static final String Tab_jtree = "Tab_jtree";

    /** The resolved runtime value of constant 'Tab_jtree', or null. */
    public static String Tab_jtree(){
        try{ return dataInterface.getVariable("Tab_jtree"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jpan" */
    public static final String Tab_jpan = "Tab_jpan";

    /** The resolved runtime value of constant 'Tab_jpan', or null. */
    public static String Tab_jpan(){
        try{ return dataInterface.getVariable("Tab_jpan"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_basc_comp" */
    public static final String Tab_basc_comp = "Tab_basc_comp";

    /** The resolved runtime value of constant 'Tab_basc_comp', or null. */
    public static String Tab_basc_comp(){
        try{ return dataInterface.getVariable("Tab_basc_comp"); }
        catch(Exception x){ return null; }
    }

    /** "Tab_jtree2" */
    public static final String Tab_jtree2 = "Tab_jtree2";

    /** The resolved runtime value of constant 'Tab_jtree2', or null. */
    public static String Tab_jtree2(){
        try{ return dataInterface.getVariable("Tab_jtree2"); }
        catch(Exception x){ return null; }
    }

    /** "FormsTest" */
    public static final String FormsTest = "FormsTest";

    /** The resolved runtime value of constant 'FormsTest', or null. */
    public static String FormsTest(){
        try{ return dataInterface.getVariable("FormsTest"); }
        catch(Exception x){ return null; }
    }

    /** "FormsBrowser" */
    public static final String FormsBrowser = "FormsBrowser";

    /** The resolved runtime value of constant 'FormsBrowser', or null. */
    public static String FormsBrowser(){
        try{ return dataInterface.getVariable("FormsBrowser"); }
        catch(Exception x){ return null; }
    }

    /** "AmazonText" */
    public static final String AmazonText = "AmazonText";

    /** The resolved runtime value of constant 'AmazonText', or null. */
    public static String AmazonText(){
        try{ return dataInterface.getVariable("AmazonText"); }
        catch(Exception x){ return null; }
    }

    /** "FormsURL" */
    public static final String FormsURL = "FormsURL";

    /** The resolved runtime value of constant 'FormsURL', or null. */
    public static String FormsURL(){
        try{ return dataInterface.getVariable("FormsURL"); }
        catch(Exception x){ return null; }
    }

    /** "SampleEscpScript" */
    public static final String SampleEscpScript = "SampleEscpScript";

    /** The resolved runtime value of constant 'SampleEscpScript', or null. */
    public static String SampleEscpScript(){
        try{ return dataInterface.getVariable("SampleEscpScript"); }
        catch(Exception x){ return null; }
    }

    // The Names of Window and Child Component objects: 

    /** "ContentSelector" Component and its children. */
    public static class ContentSelector {

        // No use for a default constructor.
        private ContentSelector(){}

        /** "ContentSelector" Window Component itself. */
        public static final Component ContentSelector = new Component("ContentSelector");

        /** "Result" Component in "ContentSelector". */
        public static final Component Result = new Component(ContentSelector, "Result");
    }

    /** "SwingApp" Component and its children. */
    public static class SwingApp {

        // No use for a default constructor.
        private SwingApp(){}

        /** "SwingApp" Window Component itself. */
        public static final Component SwingApp = new Component("SwingApp");

        /** "JDragTab" Component in "SwingApp". */
        public static final Component JDragTab = new Component(SwingApp, "JDragTab");

        /** "TitleBar" Component in "SwingApp". */
        public static final Component TitleBar = new Component(SwingApp, "TitleBar");
    }

    /** "Notepad" Component and its children. */
    public static class Notepad {

        // No use for a default constructor.
        private Notepad(){}

        /** "Notepad" Window Component itself. */
        public static final Component Notepad = new Component("Notepad");

        /** "EditBox" Component in "Notepad". */
        public static final Component EditBox = new Component(Notepad, "EditBox");
    }

    /** "FormsMain" Component and its children. */
    public static class FormsMain {

        // No use for a default constructor.
        private FormsMain(){}

        /** "FormsMain" Window Component itself. */
        public static final Component FormsMain = new Component("FormsMain");

        /** "CheckBox3" Component in "FormsMain". */
        public static final Component CheckBox3 = new Component(FormsMain, "CheckBox3");

        /** "CheckBox2" Component in "FormsMain". */
        public static final Component CheckBox2 = new Component(FormsMain, "CheckBox2");

        /** "CheckBox1" Component in "FormsMain". */
        public static final Component CheckBox1 = new Component(FormsMain, "CheckBox1");

        /** "MultiLineText" Component in "FormsMain". */
        public static final Component MultiLineText = new Component(FormsMain, "MultiLineText");

        /** "SingleLineText" Component in "FormsMain". */
        public static final Component SingleLineText = new Component(FormsMain, "SingleLineText");
    }

    /** "GoogleResults" Component and its children. */
    public static class GoogleResults {

        // No use for a default constructor.
        private GoogleResults(){}

        /** "GoogleResults" Window Component itself. */
        public static final Component GoogleResults = new Component("GoogleResults");

        /** "AmazonAdCite" Component in "GoogleResults". */
        public static final Component AmazonAdCite = new Component(GoogleResults, "AmazonAdCite");

        /** "AmazonOfficialSiteLink" Component in "GoogleResults". */
        public static final Component AmazonOfficialSiteLink = new Component(GoogleResults, "AmazonOfficialSiteLink");
    }

    /** "Bing" Component and its children. */
    public static class Bing {

        // No use for a default constructor.
        private Bing(){}

        /** "Bing" Window Component itself. */
        public static final Component Bing = new Component("Bing");

        /** "TabImage" Component in "Bing". */
        public static final Component TabImage = new Component(Bing, "TabImage");

        /** "SearchButton" Component in "Bing". */
        public static final Component SearchButton = new Component(Bing, "SearchButton");

        /** "SearchInput" Component in "Bing". */
        public static final Component SearchInput = new Component(Bing, "SearchInput");

        /** "FirstImage" Component in "Bing". */
        public static final Component FirstImage = new Component(Bing, "FirstImage");
    }

    /** "IBTWinIR" Component and its children. */
    public static class IBTWinIR {

        // No use for a default constructor.
        private IBTWinIR(){}

        /** "IBTWinIR" Window Component itself. */
        public static final Component IBTWinIR = new Component("IBTWinIR");

        /** "JDragTab" Component in "IBTWinIR". */
        public static final Component JDragTab = new Component(IBTWinIR, "JDragTab");

        /** "TitleBar" Component in "IBTWinIR". */
        public static final Component TitleBar = new Component(IBTWinIR, "TitleBar");
    }

    /** "InternalSecondPage" Component and its children. */
    public static class InternalSecondPage {

        // No use for a default constructor.
        private InternalSecondPage(){}

        /** "InternalSecondPage" Window Component itself. */
        public static final Component InternalSecondPage = new Component("InternalSecondPage");
    }

    /** "ApplicationConstants" Component and its children. */
    public static class ApplicationConstants {

        // No use for a default constructor.
        private ApplicationConstants(){}

        /** "ApplicationConstants" Window Component itself. */
        public static final Component ApplicationConstants = new Component("ApplicationConstants");

        /** "DOJO_CHART_URL" Component in "ApplicationConstants". */
        public static final Component DOJO_CHART_URL = new Component(ApplicationConstants, "DOJO_CHART_URL");

        /** "subarea" Component in "ApplicationConstants". */
        public static final Component subarea = new Component(ApplicationConstants, "subarea");

        /** "LocationKey" Component in "ApplicationConstants". */
        public static final Component LocationKey = new Component(ApplicationConstants, "LocationKey");

        /** "W3CConfirmURL" Component in "ApplicationConstants". */
        public static final Component W3CConfirmURL = new Component(ApplicationConstants, "W3CConfirmURL");

        /** "GOJS_MINIMAL_URL" Component in "ApplicationConstants". */
        public static final Component GOJS_MINIMAL_URL = new Component(ApplicationConstants, "GOJS_MINIMAL_URL");

        /** "THOMAS_BAYER_SQLREST_PRODUCT_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_PRODUCT_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_PRODUCT_URL");

        /** "THOMAS_BAYER_SQLREST_INVOICE_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_INVOICE_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_INVOICE_URL");

        /** "HtmlLinkTargetPageURL" Component in "ApplicationConstants". */
        public static final Component HtmlLinkTargetPageURL = new Component(ApplicationConstants, "HtmlLinkTargetPageURL");

        /** "THOMAS_BAYER_SQLREST_ITEM_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_ITEM_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_ITEM_URL");

        /** "W3CAlertURL" Component in "ApplicationConstants". */
        public static final Component W3CAlertURL = new Component(ApplicationConstants, "W3CAlertURL");

        /** "InternalSecondPageURL" Component in "ApplicationConstants". */
        public static final Component InternalSecondPageURL = new Component(ApplicationConstants, "InternalSecondPageURL");

        /** "W3CPromptURL" Component in "ApplicationConstants". */
        public static final Component W3CPromptURL = new Component(ApplicationConstants, "W3CPromptURL");

        /** "THOMAS_BAYER_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_URL = new Component(ApplicationConstants, "THOMAS_BAYER_URL");

        /** "THOMAS_BAYER_SQLREST_CUSTOMER_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_CUSTOMER_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_CUSTOMER_URL");

        /** "InternalTestLinkPageURL" Component in "ApplicationConstants". */
        public static final Component InternalTestLinkPageURL = new Component(ApplicationConstants, "InternalTestLinkPageURL");

        /** "THOMAS_BAYER_SQLREST_URL" Component in "ApplicationConstants". */
        public static final Component THOMAS_BAYER_SQLREST_URL = new Component(ApplicationConstants, "THOMAS_BAYER_SQLREST_URL");

        /** "SwingAppID" Component in "ApplicationConstants". */
        public static final Component SwingAppID = new Component(ApplicationConstants, "SwingAppID");

        /** "SwingAppJar" Component in "ApplicationConstants". */
        public static final Component SwingAppJar = new Component(ApplicationConstants, "SwingAppJar");

        /** "UserNamespaceURIBench" Component in "ApplicationConstants". */
        public static final Component UserNamespaceURIBench = new Component(ApplicationConstants, "UserNamespaceURIBench");

        /** "HoneycombURL" Component in "ApplicationConstants". */
        public static final Component HoneycombURL = new Component(ApplicationConstants, "HoneycombURL");

        /** "TestPath" Component in "ApplicationConstants". */
        public static final Component TestPath = new Component(ApplicationConstants, "TestPath");

        /** "SignInInfoScreenshot" Component in "ApplicationConstants". */
        public static final Component SignInInfoScreenshot = new Component(ApplicationConstants, "SignInInfoScreenshot");

        /** "SignInBenchmark" Component in "ApplicationConstants". */
        public static final Component SignInBenchmark = new Component(ApplicationConstants, "SignInBenchmark");

        /** "GoogleUser" Component in "ApplicationConstants". */
        public static final Component GoogleUser = new Component(ApplicationConstants, "GoogleUser");

        /** "HoneycombBrowser" Component in "ApplicationConstants". */
        public static final Component HoneycombBrowser = new Component(ApplicationConstants, "HoneycombBrowser");

        /** "GooglePassword" Component in "ApplicationConstants". */
        public static final Component GooglePassword = new Component(ApplicationConstants, "GooglePassword");

        /** "Platform" Component in "ApplicationConstants". */
        public static final Component Platform = new Component(ApplicationConstants, "Platform");

        /** "SignInScreenshot" Component in "ApplicationConstants". */
        public static final Component SignInScreenshot = new Component(ApplicationConstants, "SignInScreenshot");

        /** "BingURL" Component in "ApplicationConstants". */
        public static final Component BingURL = new Component(ApplicationConstants, "BingURL");

        /** "UserNamespaceURIOut" Component in "ApplicationConstants". */
        public static final Component UserNamespaceURIOut = new Component(ApplicationConstants, "UserNamespaceURIOut");

        /** "Browser" Component in "ApplicationConstants". */
        public static final Component Browser = new Component(ApplicationConstants, "Browser");

        /** "EVBBPassword" Component in "ApplicationConstants". */
        public static final Component EVBBPassword = new Component(ApplicationConstants, "EVBBPassword");

        /** "EVUserName" Component in "ApplicationConstants". */
        public static final Component EVUserName = new Component(ApplicationConstants, "EVUserName");

        /** "nlsSignin" Component in "ApplicationConstants". */
        public static final Component nlsSignin = new Component(ApplicationConstants, "nlsSignin");

        /** "GoogleBrowser" Component in "ApplicationConstants". */
        public static final Component GoogleBrowser = new Component(ApplicationConstants, "GoogleBrowser");

        /** "MessagesURL" Component in "ApplicationConstants". */
        public static final Component MessagesURL = new Component(ApplicationConstants, "MessagesURL");

        /** "EVBBUserName" Component in "ApplicationConstants". */
        public static final Component EVBBUserName = new Component(ApplicationConstants, "EVBBUserName");

        /** "ContentSelectorURL" Component in "ApplicationConstants". */
        public static final Component ContentSelectorURL = new Component(ApplicationConstants, "ContentSelectorURL");

        /** "BusyDialogURL" Component in "ApplicationConstants". */
        public static final Component BusyDialogURL = new Component(ApplicationConstants, "BusyDialogURL");

        /** "TopLeft" Component in "ApplicationConstants". */
        public static final Component TopLeft = new Component(ApplicationConstants, "TopLeft");

        /** "SimpleTableURL" Component in "ApplicationConstants". */
        public static final Component SimpleTableURL = new Component(ApplicationConstants, "SimpleTableURL");

        /** "GoogleURL" Component in "ApplicationConstants". */
        public static final Component GoogleURL = new Component(ApplicationConstants, "GoogleURL");

        /** "BenchPath" Component in "ApplicationConstants". */
        public static final Component BenchPath = new Component(ApplicationConstants, "BenchPath");

        /** "EVPassword" Component in "ApplicationConstants". */
        public static final Component EVPassword = new Component(ApplicationConstants, "EVPassword");

        /** "TestBrowserName" Component in "ApplicationConstants". */
        public static final Component TestBrowserName = new Component(ApplicationConstants, "TestBrowserName");

        /** "Tab_jtable2" Component in "ApplicationConstants". */
        public static final Component Tab_jtable2 = new Component(ApplicationConstants, "Tab_jtable2");

        /** "Tab_jtable" Component in "ApplicationConstants". */
        public static final Component Tab_jtable = new Component(ApplicationConstants, "Tab_jtable");

        /** "FilteredAreas2" Component in "ApplicationConstants". */
        public static final Component FilteredAreas2 = new Component(ApplicationConstants, "FilteredAreas2");

        /** "FilteredAreas1" Component in "ApplicationConstants". */
        public static final Component FilteredAreas1 = new Component(ApplicationConstants, "FilteredAreas1");

        /** "Tab_mort_calc" Component in "ApplicationConstants". */
        public static final Component Tab_mort_calc = new Component(ApplicationConstants, "Tab_mort_calc");

        /** "locationA" Component in "ApplicationConstants". */
        public static final Component locationA = new Component(ApplicationConstants, "locationA");

        /** "SAPDemoURL" Component in "ApplicationConstants". */
        public static final Component SAPDemoURL = new Component(ApplicationConstants, "SAPDemoURL");

        /** "Tab_jtree" Component in "ApplicationConstants". */
        public static final Component Tab_jtree = new Component(ApplicationConstants, "Tab_jtree");

        /** "Tab_jpan" Component in "ApplicationConstants". */
        public static final Component Tab_jpan = new Component(ApplicationConstants, "Tab_jpan");

        /** "Tab_basc_comp" Component in "ApplicationConstants". */
        public static final Component Tab_basc_comp = new Component(ApplicationConstants, "Tab_basc_comp");

        /** "Tab_jtree2" Component in "ApplicationConstants". */
        public static final Component Tab_jtree2 = new Component(ApplicationConstants, "Tab_jtree2");

        /** "FormsTest" Component in "ApplicationConstants". */
        public static final Component FormsTest = new Component(ApplicationConstants, "FormsTest");

        /** "FormsBrowser" Component in "ApplicationConstants". */
        public static final Component FormsBrowser = new Component(ApplicationConstants, "FormsBrowser");

        /** "AmazonText" Component in "ApplicationConstants". */
        public static final Component AmazonText = new Component(ApplicationConstants, "AmazonText");

        /** "FormsURL" Component in "ApplicationConstants". */
        public static final Component FormsURL = new Component(ApplicationConstants, "FormsURL");

        /** "SampleEscpScript" Component in "ApplicationConstants". */
        public static final Component SampleEscpScript = new Component(ApplicationConstants, "SampleEscpScript");
    }

    /** "SimpleTable" Component and its children. */
    public static class SimpleTable {

        // No use for a default constructor.
        private SimpleTable(){}

        /** "SimpleTable" Window Component itself. */
        public static final Component SimpleTable = new Component("SimpleTable");

        /** "VScroller" Component in "SimpleTable". */
        public static final Component VScroller = new Component(SimpleTable, "VScroller");

        /** "Table" Component in "SimpleTable". */
        public static final Component Table = new Component(SimpleTable, "Table");
    }

    /** "SASEV" Component and its children. */
    public static class SASEV {

        // No use for a default constructor.
        private SASEV(){}

        /** "SASEV" Window Component itself. */
        public static final Component SASEV = new Component("SASEV");

        /** "GridManagerItem" Component in "SASEV". */
        public static final Component GridManagerItem = new Component(SASEV, "GridManagerItem");

        /** "Password" Component in "SASEV". */
        public static final Component Password = new Component(SASEV, "Password");

        /** "Submit" Component in "SASEV". */
        public static final Component Submit = new Component(SASEV, "Submit");

        /** "AnalyzeMenu" Component in "SASEV". */
        public static final Component AnalyzeMenu = new Component(SASEV, "AnalyzeMenu");

        /** "SignOut" Component in "SASEV". */
        public static final Component SignOut = new Component(SASEV, "SignOut");

        /** "UserName" Component in "SASEV". */
        public static final Component UserName = new Component(SASEV, "UserName");
    }

    /** "InternalTestLinkPage" Component and its children. */
    public static class InternalTestLinkPage {

        // No use for a default constructor.
        private InternalTestLinkPage(){}

        /** "InternalTestLinkPage" Window Component itself. */
        public static final Component InternalTestLinkPage = new Component("InternalTestLinkPage");

        /** "Link" Component in "InternalTestLinkPage". */
        public static final Component Link = new Component(InternalTestLinkPage, "Link");

        /** "Body" Component in "InternalTestLinkPage". */
        public static final Component Body = new Component(InternalTestLinkPage, "Body");
    }

    /** "GoJSSamples" Component and its children. */
    public static class GoJSSamples {

        // No use for a default constructor.
        private GoJSSamples(){}

        /** "GoJSSamples" Window Component itself. */
        public static final Component GoJSSamples = new Component("GoJSSamples");

        /** "MenuPageFlow" Component in "GoJSSamples". */
        public static final Component MenuPageFlow = new Component(GoJSSamples, "MenuPageFlow");

        /** "Diagram" Component in "GoJSSamples". */
        public static final Component Diagram = new Component(GoJSSamples, "Diagram");

        /** "Palette" Component in "GoJSSamples". */
        public static final Component Palette = new Component(GoJSSamples, "Palette");
    }

    /** "W3CAlertPage" Component and its children. */
    public static class W3CAlertPage {

        // No use for a default constructor.
        private W3CAlertPage(){}

        /** "W3CAlertPage" Window Component itself. */
        public static final Component W3CAlertPage = new Component("W3CAlertPage");

        /** "Button" Component in "W3CAlertPage". */
        public static final Component Button = new Component(W3CAlertPage, "Button");
    }

    /** "SAPDemoPage" Component and its children. */
    public static class SAPDemoPage {

        // No use for a default constructor.
        private SAPDemoPage(){}

        /** "SAPDemoPage" Window Component itself. */
        public static final Component SAPDemoPage = new Component("SAPDemoPage");

        /** "ListViewItemFederated" Component in "SAPDemoPage". */
        public static final Component ListViewItemFederated = new Component(SAPDemoPage, "ListViewItemFederated");

        /** "Basc_ListBox" Component in "SAPDemoPage". */
        public static final Component Basc_ListBox = new Component(SAPDemoPage, "Basc_ListBox");

        /** "Basc_TextArea" Component in "SAPDemoPage". */
        public static final Component Basc_TextArea = new Component(SAPDemoPage, "Basc_TextArea");

        /** "Basc_Link" Component in "SAPDemoPage". */
        public static final Component Basc_Link = new Component(SAPDemoPage, "Basc_Link");

        /** "ListViewItemArizona" Component in "SAPDemoPage". */
        public static final Component ListViewItemArizona = new Component(SAPDemoPage, "ListViewItemArizona");

        /** "TabControl" Component in "SAPDemoPage". */
        public static final Component TabControl = new Component(SAPDemoPage, "TabControl");

        /** "JPan_Postcode" Component in "SAPDemoPage". */
        public static final Component JPan_Postcode = new Component(SAPDemoPage, "JPan_Postcode");

        /** "Basc_ComboBox" Component in "SAPDemoPage". */
        public static final Component Basc_ComboBox = new Component(SAPDemoPage, "Basc_ComboBox");

        /** "ListViewItem5" Component in "SAPDemoPage". */
        public static final Component ListViewItem5 = new Component(SAPDemoPage, "ListViewItem5");

        /** "Basc_Password" Component in "SAPDemoPage". */
        public static final Component Basc_Password = new Component(SAPDemoPage, "Basc_Password");

        /** "ListViewItem26" Component in "SAPDemoPage". */
        public static final Component ListViewItem26 = new Component(SAPDemoPage, "ListViewItem26");

        /** "JPan_LastName" Component in "SAPDemoPage". */
        public static final Component JPan_LastName = new Component(SAPDemoPage, "JPan_LastName");

        /** "MenuBar" Component in "SAPDemoPage". */
        public static final Component MenuBar = new Component(SAPDemoPage, "MenuBar");

        /** "Basc_Radio" Component in "SAPDemoPage". */
        public static final Component Basc_Radio = new Component(SAPDemoPage, "Basc_Radio");

        /** "JPan_Address_L" Component in "SAPDemoPage". */
        public static final Component JPan_Address_L = new Component(SAPDemoPage, "JPan_Address_L");

        /** "JPan_FirstName_L" Component in "SAPDemoPage". */
        public static final Component JPan_FirstName_L = new Component(SAPDemoPage, "JPan_FirstName_L");

        /** "Basc_Password_L" Component in "SAPDemoPage". */
        public static final Component Basc_Password_L = new Component(SAPDemoPage, "Basc_Password_L");

        /** "Basc_Input_L" Component in "SAPDemoPage". */
        public static final Component Basc_Input_L = new Component(SAPDemoPage, "Basc_Input_L");

        /** "MenuBasicComponentsItem" Component in "SAPDemoPage". */
        public static final Component MenuBasicComponentsItem = new Component(SAPDemoPage, "MenuBasicComponentsItem");

        /** "Basc_CheckBox" Component in "SAPDemoPage". */
        public static final Component Basc_CheckBox = new Component(SAPDemoPage, "Basc_CheckBox");

        /** "TreeView" Component in "SAPDemoPage". */
        public static final Component TreeView = new Component(SAPDemoPage, "TreeView");

        /** "ListView" Component in "SAPDemoPage". */
        public static final Component ListView = new Component(SAPDemoPage, "ListView");

        /** "ListViewItemAlaska" Component in "SAPDemoPage". */
        public static final Component ListViewItemAlaska = new Component(SAPDemoPage, "ListViewItemAlaska");

        /** "MenuToolViewerItem" Component in "SAPDemoPage". */
        public static final Component MenuToolViewerItem = new Component(SAPDemoPage, "MenuToolViewerItem");

        /** "MenuToolsItem" Component in "SAPDemoPage". */
        public static final Component MenuToolsItem = new Component(SAPDemoPage, "MenuToolsItem");

        /** "ListViewItemAr" Component in "SAPDemoPage". */
        public static final Component ListViewItemAr = new Component(SAPDemoPage, "ListViewItemAr");

        /** "JPan_Postcode_L" Component in "SAPDemoPage". */
        public static final Component JPan_Postcode_L = new Component(SAPDemoPage, "JPan_Postcode_L");

        /** "JPan_Employee" Component in "SAPDemoPage". */
        public static final Component JPan_Employee = new Component(SAPDemoPage, "JPan_Employee");

        /** "JPan_Employee_L" Component in "SAPDemoPage". */
        public static final Component JPan_Employee_L = new Component(SAPDemoPage, "JPan_Employee_L");

        /** "JPan_LastName_L" Component in "SAPDemoPage". */
        public static final Component JPan_LastName_L = new Component(SAPDemoPage, "JPan_LastName_L");

        /** "JPan_FirstName" Component in "SAPDemoPage". */
        public static final Component JPan_FirstName = new Component(SAPDemoPage, "JPan_FirstName");

        /** "Basc_TextArea_L" Component in "SAPDemoPage". */
        public static final Component Basc_TextArea_L = new Component(SAPDemoPage, "Basc_TextArea_L");

        /** "Basc_Button" Component in "SAPDemoPage". */
        public static final Component Basc_Button = new Component(SAPDemoPage, "Basc_Button");

        /** "Basc_Input" Component in "SAPDemoPage". */
        public static final Component Basc_Input = new Component(SAPDemoPage, "Basc_Input");

        /** "JPan_Address" Component in "SAPDemoPage". */
        public static final Component JPan_Address = new Component(SAPDemoPage, "JPan_Address");

        /** "Basc_ToggleButton" Component in "SAPDemoPage". */
        public static final Component Basc_ToggleButton = new Component(SAPDemoPage, "Basc_ToggleButton");
    }

    /** "HtmlLinkTargetPage" Component and its children. */
    public static class HtmlLinkTargetPage {

        // No use for a default constructor.
        private HtmlLinkTargetPage(){}

        /** "HtmlLinkTargetPage" Window Component itself. */
        public static final Component HtmlLinkTargetPage = new Component("HtmlLinkTargetPage");

        /** "Link" Component in "HtmlLinkTargetPage". */
        public static final Component Link = new Component(HtmlLinkTargetPage, "Link");

        /** "Body" Component in "HtmlLinkTargetPage". */
        public static final Component Body = new Component(HtmlLinkTargetPage, "Body");
    }

    /** "IBTWinSR" Component and its children. */
    public static class IBTWinSR {

        // No use for a default constructor.
        private IBTWinSR(){}

        /** "IBTWinSR" Window Component itself. */
        public static final Component IBTWinSR = new Component("IBTWinSR");

        /** "JDragTab" Component in "IBTWinSR". */
        public static final Component JDragTab = new Component(IBTWinSR, "JDragTab");

        /** "TitleBar" Component in "IBTWinSR". */
        public static final Component TitleBar = new Component(IBTWinSR, "TitleBar");
    }

    /** "Calculator" Component and its children. */
    public static class Calculator {

        // No use for a default constructor.
        private Calculator(){}

        /** "Calculator" Window Component itself. */
        public static final Component Calculator = new Component("Calculator");

        /** "BtnMinus" Component in "Calculator". */
        public static final Component BtnMinus = new Component(Calculator, "BtnMinus");

        /** "Panel" Component in "Calculator". */
        public static final Component Panel = new Component(Calculator, "Panel");

        /** "Btn9" Component in "Calculator". */
        public static final Component Btn9 = new Component(Calculator, "Btn9");

        /** "Btn8" Component in "Calculator". */
        public static final Component Btn8 = new Component(Calculator, "Btn8");

        /** "Btn7" Component in "Calculator". */
        public static final Component Btn7 = new Component(Calculator, "Btn7");

        /** "Btn6" Component in "Calculator". */
        public static final Component Btn6 = new Component(Calculator, "Btn6");

        /** "Btn5" Component in "Calculator". */
        public static final Component Btn5 = new Component(Calculator, "Btn5");

        /** "Btn4" Component in "Calculator". */
        public static final Component Btn4 = new Component(Calculator, "Btn4");

        /** "Btn3" Component in "Calculator". */
        public static final Component Btn3 = new Component(Calculator, "Btn3");

        /** "Btn2" Component in "Calculator". */
        public static final Component Btn2 = new Component(Calculator, "Btn2");

        /** "Btn1" Component in "Calculator". */
        public static final Component Btn1 = new Component(Calculator, "Btn1");

        /** "Btn0" Component in "Calculator". */
        public static final Component Btn0 = new Component(Calculator, "Btn0");

        /** "BtnDiv" Component in "Calculator". */
        public static final Component BtnDiv = new Component(Calculator, "BtnDiv");

        /** "BtnEqual" Component in "Calculator". */
        public static final Component BtnEqual = new Component(Calculator, "BtnEqual");

        /** "BtnPlus" Component in "Calculator". */
        public static final Component BtnPlus = new Component(Calculator, "BtnPlus");

        /** "BtnMulp" Component in "Calculator". */
        public static final Component BtnMulp = new Component(Calculator, "BtnMulp");
    }

    /** "IBTWin0R" Component and its children. */
    public static class IBTWin0R {

        // No use for a default constructor.
        private IBTWin0R(){}

        /** "IBTWin0R" Window Component itself. */
        public static final Component IBTWin0R = new Component("IBTWin0R");

        /** "JDragTab" Component in "IBTWin0R". */
        public static final Component JDragTab = new Component(IBTWin0R, "JDragTab");

        /** "TitleBar" Component in "IBTWin0R". */
        public static final Component TitleBar = new Component(IBTWin0R, "TitleBar");
    }

    /** "Google" Component and its children. */
    public static class Google {

        // No use for a default constructor.
        private Google(){}

        /** "Google" Window Component itself. */
        public static final Component Google = new Component("Google");

        /** "SearchBox" Component in "Google". */
        public static final Component SearchBox = new Component(Google, "SearchBox");

        /** "SignIn" Component in "Google". */
        public static final Component SignIn = new Component(Google, "SignIn");
    }

    /** "DynamicChart" Component and its children. */
    public static class DynamicChart {

        // No use for a default constructor.
        private DynamicChart(){}

        /** "DynamicChart" Window Component itself. */
        public static final Component DynamicChart = new Component("DynamicChart");

        /** "Serie1Btn" Component in "DynamicChart". */
        public static final Component Serie1Btn = new Component(DynamicChart, "Serie1Btn");

        /** "GridCheckBox" Component in "DynamicChart". */
        public static final Component GridCheckBox = new Component(DynamicChart, "GridCheckBox");

        /** "ComboBox" Component in "DynamicChart". */
        public static final Component ComboBox = new Component(DynamicChart, "ComboBox");

        /** "Serie5Btn" Component in "DynamicChart". */
        public static final Component Serie5Btn = new Component(DynamicChart, "Serie5Btn");

        /** "XCheckBox" Component in "DynamicChart". */
        public static final Component XCheckBox = new Component(DynamicChart, "XCheckBox");

        /** "YCheckBox" Component in "DynamicChart". */
        public static final Component YCheckBox = new Component(DynamicChart, "YCheckBox");
    }

    /** "W3CPage" Component and its children. */
    public static class W3CPage {

        // No use for a default constructor.
        private W3CPage(){}

        /** "W3CPage" Window Component itself. */
        public static final Component W3CPage = new Component("W3CPage");
    }

    /** "T.Window" Component and its children. */
    public static class T_Window {

        // No use for a default constructor.
        private T_Window(){}

        /** "T.Window" Window Component itself. */
        public static final Component T_Window = new Component("T.Window");

        /** "T.Component" Component in "T.Window". */
        public static final Component T_Component = new Component(T_Window, "T.Component");
    }

    /** "Basc_ListBox" Component and its children. */
    public static class Basc_ListBox {

        // No use for a default constructor.
        private Basc_ListBox(){}

        /** "Basc_ListBox" Window Component itself. */
        public static final Component Basc_ListBox = new Component("Basc_ListBox");

        /** "FilteredAreasWithError" Component in "Basc_ListBox". */
        public static final Component FilteredAreasWithError = new Component(Basc_ListBox, "FilteredAreasWithError");

        /** "FilteredAreasWithWarning" Component in "Basc_ListBox". */
        public static final Component FilteredAreasWithWarning = new Component(Basc_ListBox, "FilteredAreasWithWarning");
    }

    /** "ThomasBayerPage" Component and its children. */
    public static class ThomasBayerPage {

        // No use for a default constructor.
        private ThomasBayerPage(){}

        /** "ThomasBayerPage" Window Component itself. */
        public static final Component ThomasBayerPage = new Component("ThomasBayerPage");
    }

    /** "Notepad_Replace" Component and its children. */
    public static class Notepad_Replace {

        // No use for a default constructor.
        private Notepad_Replace(){}

        /** "Notepad_Replace" Window Component itself. */
        public static final Component Notepad_Replace = new Component("Notepad_Replace");

        /** "EditBoxReplace" Component in "Notepad_Replace". */
        public static final Component EditBoxReplace = new Component(Notepad_Replace, "EditBoxReplace");

        /** "ButtonReplaceAll" Component in "Notepad_Replace". */
        public static final Component ButtonReplaceAll = new Component(Notepad_Replace, "ButtonReplaceAll");

        /** "EditBoxFind" Component in "Notepad_Replace". */
        public static final Component EditBoxFind = new Component(Notepad_Replace, "EditBoxFind");

        /** "ButtonCancel" Component in "Notepad_Replace". */
        public static final Component ButtonCancel = new Component(Notepad_Replace, "ButtonCancel");
    }

    /** "LogIn" Component and its children. */
    public static class LogIn {

        // No use for a default constructor.
        private LogIn(){}

        /** "LogIn" Window Component itself. */
        public static final Component LogIn = new Component("LogIn");

        /** "Circle" Component in "LogIn". */
        public static final Component Circle = new Component(LogIn, "Circle");

        /** "BackArrow" Component in "LogIn". */
        public static final Component BackArrow = new Component(LogIn, "BackArrow");

        /** "SignIn" Component in "LogIn". */
        public static final Component SignIn = new Component(LogIn, "SignIn");

        /** "ProfileImage" Component in "LogIn". */
        public static final Component ProfileImage = new Component(LogIn, "ProfileImage");

        /** "UserNameNext" Component in "LogIn". */
        public static final Component UserNameNext = new Component(LogIn, "UserNameNext");

        /** "OneGoogle" Component in "LogIn". */
        public static final Component OneGoogle = new Component(LogIn, "OneGoogle");

        /** "Passwd" Component in "LogIn". */
        public static final Component Passwd = new Component(LogIn, "Passwd");

        /** "UserName" Component in "LogIn". */
        public static final Component UserName = new Component(LogIn, "UserName");
    }

    /** "RandomClicks" Component and its children. */
    public static class RandomClicks {

        // No use for a default constructor.
        private RandomClicks(){}

        /** "RandomClicks" Window Component itself. */
        public static final Component RandomClicks = new Component("RandomClicks");

        /** "AboutPopoverLink" Component in "RandomClicks". */
        public static final Component AboutPopoverLink = new Component(RandomClicks, "AboutPopoverLink");
    }

    /** "SAFS Monitor" Component and its children. */
    public static class SAFS_Monitor {

        // No use for a default constructor.
        private SAFS_Monitor(){}

        /** "SAFS Monitor" Window Component itself. */
        public static final Component SAFS_Monitor = new Component("SAFS Monitor");
    }
}
